repos:
  - repo: local
    hooks:
      - id: check-merge-conflict
        name: check-merge-conflict
        entry: python tools/precommit/check_merge_conflict.py
        language: system

      - id: detect-private-key
        name: detect-private-key
        entry: python tools/precommit/detect_private_key.py
        language: system

      - id: trailing-whitespace
        name: trailing-whitespace
        entry: python tools/precommit/trailing_whitespace.py
        language: system

      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: python tools/precommit/end_of_file_fixer.py
        language: system

      - id: ruff
        name: ruff
        entry: ruff check --fix
        language: system
        types_or: [python]

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types_or: [python]
